import { StyleSheet } from "react-native"

export const Colores={
    azulNormal:"#194A6E",
    naranjaClaro:"#FDB672",
    naranjaNormal:"#FD8A2B",
    naranjaOscuro:"#FF7300",
    naranjaAnuncios:"#FDB066",
    blancoMentira:"#F9F9F9",
    azulOscuro:"#092B44",
    azulClaro:"#5385B0",
    grisMentira:"#D9D9D9",
    azulDiscusion:"#B2C9DD"
}


export const GlobalStyles = StyleSheet.create({
    containerAzul:{
        flex:2,
        backgroundColor: Colores.azulNormal,
    },
    textoTitulo:{
        marginEnd:10,
        marginStart:10,
        width:"auto",
        height:80        
    },
    //login screen
    containerBlanco:{
        backgroundColor:Colores.blancoMentira,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        flex:3,
        paddingBottom:40

    },
    containerTitulo:{
        flex:1,
        flexDirection:"column",
        marginTop:"20%"
    },
    logo:{
        marginTop:"3%",
        position:"absolute",
        right:"3%"
    }
    ,
    textoAccede:{
        marginEnd:20,
        marginStart:20,
        marginTop:100
    },
    gatoPerro:{
        position: 'absolute',
        alignSelf:"center",
        flex:1,
        top:"-20%"
        
    },
    statusBar:{
        backgroundColor:Colores.azulNormal
    },
    inputContainer:{
        backgroundColor:Colores.naranjaClaro,
        paddingHorizontal:"5%",
        paddingVertical:"3%",
        borderRadius:100,
        marginHorizontal:"5%",
        borderColor:Colores.azulClaro,
        borderWidth:2
    },
    inputText:{
        fontSize:30,
        fontFamily:"Poppins"
    },
    datosContainer:{
        gap:20,
        flex:2
    },
    rememberContainer:{
        marginEnd:25,
        marginStart:25,
        paddingHorizontal:5,
        flexDirection:"row"
    },
    rememberText:{
        fontSize:22,
        fontWeight:"bold",
        fontFamily:"Poppins",
        color:Colores.azulNormal,
        marginLeft:"2%"
    },
    rememberButton:{
        backgroundColor:Colores.naranjaClaro,
        borderColor:Colores.azulNormal,
        borderWidth:2,
        borderRadius:4,
        width:"4%",
        height:"75%",
        marginLeft:"5%",
        alignSelf:"center",
        color:Colores.blancoMentira,
        fontWeight: "bold",
        opacity:0.5
    },
    accederContainer:{
        margin:25,
        flex:0.5
    },
    accederButton:{
        backgroundColor:Colores.azulNormal,
        color:Colores.blancoMentira,
        borderRadius:100,
        fontFamily:"Poppins",
        fontWeight:"bold",
        fontSize:32,
        alignContent:"center",
        paddingVertical:"2%"
    },
    accederTextContainer:{
        flexDirection:"row",
        gap:"25%"
    },
    accederText:{
        color:Colores.azulNormal,
        fontSize:20,
        fontWeight:"bold",
        textDecorationLine:"underline",
        fontFamily:"Poppins",
    },
    accesoRapidoContainer:{
        marginEnd:25,
        marginStart:30,
        flexDirection:"column"
    },
    accesoRapidoTexto:{
        fontFamily:"Poppins",
        fontWeight:"bold",
        fontSize:22,
        color:Colores.azulNormal,
    },
    accesoTextoContainer:{
        flexDirection:"row",
        flexWrap:"nowrap",
        backgroundColor:Colores.naranjaNormal
    },
    accesoLinea:{
        borderBottomColor: Colores.naranjaNormal,
        height: 0.9,
        backgroundColor:Colores.naranjaNormal,
        width:"20%",
        alignSelf:"center",
        
    },
    lineaI:{
        marginRight:"-20%",
        marginLeft:"10%"
    },
    lineaD:{
        marginLeft:"-20%"
    },
    accesoLogosContainer:{
        flexDirection:"row",
        gap:"10%",
        alignItems:"center",
        marginTop:20,
        marginBottom:20,
        justifyContent:"center"
    },
    //inicio screen
    containerBlancoInicio:{
        backgroundColor:Colores.grisMentira,
        flex:3,
        borderTopEndRadius:10,
        borderTopStartRadius:10,
        paddingBottom:40
    },
    header:{
        flexDirection:"row",
        marginTop:"2%",
        marginStart:"5%",
        marginEnd:"5%",
        alignItems:"center",
        justifyContent:"space-between",
        gap:"8%"
    },
    headerTextoInicio:{
        fontFamily:"MoreSugar",
        color:Colores.blancoMentira,
        fontSize:75,
    },
    directorContainer:{
        flexDirection:"column",
        alignItems:"center",
    },
    directorTexto:{
        
        fontFamily:"Poppins",
        fontSize:36,
        fontWeight:"bold",
        color:Colores.blancoMentira
    },
    directorIdentificador:{
        fontSize:24,
        fontFamily:"Poppins",
        color:Colores.naranjaClaro,
        fontWeight:"normal",
        marginTop:-10,
        marginBottom:15
    },
    menuContainer:{
        flexDirection:"column",
        justifyContent:"space-evenly",
        paddingStart:"5%",
        paddingEnd:"5%",
        paddingTop:"1%",
        gap:"1%"

    },
    menuElemento:{
        flexDirection:"row",
        flex:1,
        gap:"10%",
        alignItems:"center"
    },
    menuElementoTexto:{
        fontFamily:"Poppins",
        fontSize:40,
        color:Colores.azulNormal,
    }
    ,
    protectorasContainer:{
        backgroundColor:Colores.azulNormal,
        borderTopEndRadius:10,
        borderTopStartRadius:10,
        flexDirection:"column",
        fontFamily:"Poppins",
        fontSize:32,
        color:Colores.blancoMentira,
        fontWeight:"bold",
        alignItems:"center",
        paddingTop:"2%",
        gap:0

    },
    protectorasImagenesContainer:{
        flexDirection:"row",
        flexWrap:"nowrap",
    },
    //comunidadScreen
    headerComunidad:{
        flexDirection:"row",
        marginTop:"2%",
        marginStart:"5%",
        marginEnd:"5%",
        alignItems:"center",
        justifyContent:"space-around",
        paddingBottom:"5%"
    },
    headerComunidadTexto:{
        fontSize:36,
        fontFamily:"MoreSugar",
        color:Colores.blancoMentira,
    },
    comunidadContainerBlanco:{
        backgroundColor:Colores.blancoMentira,
        borderTopEndRadius:10,
        borderTopStartRadius:10,
        flex:1
    },
    containerAnuncio:{
        backgroundColor:Colores.naranjaAnuncios,
        borderRadius:50,
        flexDirection:"column",
        padding:"5%",
        marginTop:"5%",
        marginHorizontal:"5%"
    },
    containerHeaderAnuncio:{
        flexDirection:"row"
    },
    textoHeaderAnuncio:{
        fontFamily:"Poppins",
        fontSize:32,
        color:Colores.azulNormal,

    },
    textoAnuncio:{
        fontFamily:"Poppins",
        fontSize:24,
        color:Colores.azulNormal,
        alignSelf:"center"
    },
    discusionContainer:{
        marginHorizontal:"5%",
        marginBottom:"2%",
        marginTop:"5%",
        flex:1
    },
    discusionTitulo:{
        color:Colores.azulNormal,
        fontWeight:"bold",
        fontSize:32
    },
    scrollContainer:{
        flexDirection:"column",
        flex:1
    },
    scrollElemento:{
        backgroundColor:Colores.azulDiscusion,
        borderRadius:25,
        paddingHorizontal:"7%",
        paddingVertical:"5%",
        marginBottom:"5%"                                                                                                                                                                                                          
    },
    elementoTexto:{
        fontFamily:"Poppins",
        fontSize:32,
        fontWeight:"bold",
        color:Colores.azulNormal

    },
    elementoBocadillo:{
        opacity:1,
        alignSelf:"center"
    },
    elementoNumero:{
        fontFamily:"Poppins",
        fontSize:48,
        color:Colores.azulNormal
    },
    bocadilloContainer:{
        justifyContent:"flex-end",
        flexDirection:"row"
    },
    nuevaDiscusionContainer:{
        backgroundColor:Colores.naranjaClaro,
        flex:0.1,
        flexDirection:"row",
        borderRadius:30,
        alignSelf:"flex-end",
        paddingHorizontal:"5%",
        marginTop:"3%",
        width:216
    },
    masDiscusion:{
        fontFamily:"Poppins",
        fontSize:64,
        color:Colores.blancoMentira,
        alignSelf:"center",
        margin:"1%",
        fontWeight:"thin"

    },
    masDiscusionTexto:{
        alignSelf:"center",
        fontFamily:"Poppins",
        fontSize:32,
        color:Colores.blancoMentira

    }
})